// <auto-generated />
using System;
using Erp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresPlanDbContext))]
    [Migration("20260516235656_AddFactoryAlerts")]
    partial class AddFactoryAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.Domain.Common.FactoryAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DismissedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("ResolvedUtc", "DismissedUtc");

                    b.ToTable("FactoryAlerts", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Common.PlanShareToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Token");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanShareTokens", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Common.SavedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Common.PlanShareToken", b =>
                {
                    b.HasOne("Erp.Domain.Common.SavedPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Common.SavedPlan", b =>
                {
                    b.OwnsMany("Erp.Domain.Common.ProductionTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("SavedPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("SavedPlanId", "__synthesizedOrdinal");

                            b1.ToTable("Plans");

                            b1.ToJson("Targets");

                            b1.WithOwner()
                                .HasForeignKey("SavedPlanId");
                        });

                    b.OwnsMany("Erp.Domain.Common.ResourceAvailability", "Available", b1 =>
                        {
                            b1.Property<Guid>("SavedPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("SavedPlanId", "__synthesizedOrdinal");

                            b1.ToTable("Plans");

                            b1.ToJson("Available");

                            b1.WithOwner()
                                .HasForeignKey("SavedPlanId");
                        });

                    b.Navigation("Available");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
