// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqlitePlanDbContext))]
    [Migration("20260515130945_AddPlanShareTokens")]
    partial class AddPlanShareTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Erp.Domain.Common.PlanShareToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Token");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanShareTokens", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Common.SavedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Common.PlanShareToken", b =>
                {
                    b.HasOne("Erp.Domain.Common.SavedPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Common.SavedPlan", b =>
                {
                    b.OwnsMany("Erp.Domain.Common.ProductionTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("SavedPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("SavedPlanId", "__synthesizedOrdinal");

                            b1.ToTable("Plans");

                            b1.ToJson("Targets");

                            b1.WithOwner()
                                .HasForeignKey("SavedPlanId");
                        });

                    b.OwnsMany("Erp.Domain.Common.ResourceAvailability", "Available", b1 =>
                        {
                            b1.Property<Guid>("SavedPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Item")
                                .IsRequired();

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("SavedPlanId", "__synthesizedOrdinal");

                            b1.ToTable("Plans");

                            b1.ToJson("Available");

                            b1.WithOwner()
                                .HasForeignKey("SavedPlanId");
                        });

                    b.Navigation("Available");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
