// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqlitePlanDbContext))]
    partial class SqlitePlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ERP.Domain.SavedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.SavedPlan", b =>
                {
                    b.OwnsMany("ERP.Domain.ProductionTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Item")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ItemId");

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("PlanId", "Ordinal");

                            b1.ToTable("PlanTargets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsMany("ERP.Domain.ResourceAvailability", "Available", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Item")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ItemId");

                            b1.Property<decimal>("ItemsPerMinute")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("PlanId", "Ordinal");

                            b1.ToTable("PlanAvailability", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("Available");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
